### ISSUE TITLE
Global lazy strategy not being applied to controllers

### ISSUE THREAD

**Issue by exts** [xamantra/momentum#27]
Here's an example of an app I have.

```dart
Momentum(
  disabledPersistentState: true,
  strategy: BootstrapStrategy.lazyFirstCall,
  controllers: [
    ItemIndexController()..config(lazy: false),
    ItemManageController(),
    LabelManageController(),
    LabelIndexController()..config(lazy: false),
    SettingsController(),
  ],
// ... snipped ...
)
```

In theory this should work fine and any time i call the `LabelManageController` for the first time it should initialize one of my services. Thing is, that doesn't work. So I had to manually set it in the `config()` for it to work like so:

```dart
Momentum(
  disabledPersistentState: true,
  strategy: BootstrapStrategy.lazyFirstCall,
  controllers: [
    ItemIndexController()..config(lazy: false),
    ItemManageController(),
    LabelManageController()
      ..config(strategy: BootstrapStrategy.lazyFirstCall),
    LabelIndexController()..config(lazy: false),
    SettingsController(),
  ],
// ... snipped ...
)
```

**Comment by xamantra** [comment]
I pushed a fix for this. Can you try to use the `dev-1.3.2` channel for momentum:

```yaml
dependencies:
  flutter:
    sdk: flutter
  momentum:
    git:
      url: https://github.com/xamantra/momentum.git
      ref: 9d212aa435f21df7c179b3c6143839067c78a25c # latest commit in "dev-1.3.2"
```
