### ISSUE TITLE
Error on new Flutter

### ISSUE THREAD

**Issue by Bilonik** [xamantra/momentum#31]
momentum-1.3.1/lib/src/momentum_base.dart:99:18: Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:momentum/src/momentum_router.dart'.
    var result = Router.getParam<T>(_mRootContext);                        

momentum_base.dart:6:1: Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:momentum/src/momentum_router.dart'.
import '../momentum.dart';

**Comment by xamantra** [comment]
I need to reproduce this.
What flutter version are using? Is it `1.20.2`?

**Comment by Bilonik** [comment]
Beta Channel Latest : 1.21.0-9.1.pre

**Comment by xamantra** [comment]
I see. I'm working right now. Will check this later.

**Comment by Bilonik** [comment]
Thanks @xamantra

**Comment by xamantra** [comment]
I found the errors and was able to fix them fine. They're just import conflicts so I just use `as` keyword for importing `Router`.

Thanks for reporting the issue @Bilonik. I really appreciated it.

I don't know when I can publish version `1.3.2` in pub.dev but for now you can try using the branch `dev-1.3.2` from this repository.

```yaml
dependencies:
  # other packages ...
  momentum:
    git:
      url: https://github.com/xamantra/momentum.git
      ref: dev-1.3.2
  # other packages ...
```

**Comment by DonnC** [comment]
@xamantra 
This error still persist on flutter `1.22.4` with latest `momentum: ^1.3.2` 
im getting this error:
```
The name 'Router' is defined in the libraries 'package:flutter/src/widgets/router.dart' and 'package:momentum/src/momentum_router.dart (via package:momentum/momentum.dart)'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
```
anyway to fix this without using a bunch of `as` and `show` statements in my code?

**Comment by xamantra** [comment]
You can try the `hide` keyword. With this, you don't need the `as` or `show` keyword anymore.
```dart
import 'package:flutter/material.dart' hide Router;
// or any import hide Router;
```

But I probably need to rename the `Router` class into something else. Like `MRouter` or `MomentumRouter`. This is my biggest mistake so far with momentum. I created a `dev-1.3.3` branch the other day locally so I might implement this one on the next update.

**Comment by DonnC** [comment]
thanks for the quick response, a rename to `MomentumRouter` will do just fine, i mean to me it makes sense. Given that im now used to anything `MomentumX` -> `MomentumService`, `MomentumController`...`MomentumRouter` sounds good in-order to avoid the default flutter `Router` which might be confusing sometimes
Will use that quick fix you suggested as i wait for a permanent fix in a new version 🙂

**Comment by xamantra** [comment]
I renamed the class into `MomentumRouter` and now you can try using the branch `dev-1.3.3` from this repository.

```yaml
dependencies:
  # other packages ...
  momentum:
    git:
      url: https://github.com/xamantra/momentum.git
      ref: 915a90cb64ec6175e3a3c65879056d186599f1ec
  # other packages ...
```

This is a GitHub repo link but there shouldn't be any problems with future commits since it's referencing a specific commit not the branch itself.
