### ISSUE TITLE
Null Sound Safety Migration

### ISSUE THREAD

**Issue by Bilonik** [xamantra/momentum#43]
Do you plan to support null safety?

**Comment by xamantra** [comment]
Yes. I plan to upgrade all my packages to null-safety.
Yesterday, I upgraded my [relative_scale](https://pub.dev/packages/relative_scale) package to null-safety.
I think for `momentum` it might take longer though.

**Comment by xamantra** [comment]
Ok so. I'm now currently migrating this to null-safety.
I **decided to do it by hand** because the `dart migrate` command produced a lot of errors after and when I tried to fix them all, a lot of unit tests failed.

**Comment by xamantra** [comment]
All unit tests need to pass without any edits in the test codes.

**Comment by xamantra** [comment]
Okay so. This is harder than I've thought.
This won't be done today. I'll continue tomorrow.

**Comment by xamantra** [comment]
**Migrated to null safety now!**
Can be used from momentum's `dev` latest commit:
```yaml
dependencies:
  # other deps here
  momentum:
    git:
      url: https://github.com/xamantra/momentum.git
      ref: 5ed04cba9e859ba3802ed02a7dc24b1f84c4de27
  # other deps here
```

There are still some important things that need to be updated before publishing. Like updating readme to have null safe code. And also the entire docs website.
